# Generated by Django 4.1 on 2022-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customstaff_testimonial_work_workcategory_workimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpictures',
            name='picture',
            field=models.ImageField(upload_to='blogPicturses'),
        ),
    ]
