# Generated by Django 4.1 on 2022-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogpictures_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='smalldescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
