# Generated by Django 4.1 on 2022-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_smalldescription_alter_blog_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_picture',
            field=models.ImageField(default=1, upload_to='testimonials/clients'),
            preserve_default=False,
        ),
    ]
