# Generated by Django 4.1 on 2022-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial_client_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload a black and white png with no background in it and the logo in white.', upload_to='clients')),
                ('siteURL', models.URLField()),
            ],
        ),
    ]
