# Generated by Django 4.1 on 2022-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_new',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
