# Generated by Django 4.1 on 2022-08-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_contact_is_contacted_remove_contact_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='small_video',
            field=models.URLField(),
        ),
    ]
