# Generated by Django 4.1 on 2022-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_work_small_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='small_video',
            field=models.TextField(verbose_name='Small video uploaded in youtube Iframe Link'),
        ),
    ]
