# Generated by Django 4.1 on 2022-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_work_small_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='small_video',
            field=models.CharField(help_text='https://youtu.be/sENM2wA_FTg in this link after https://youtu.be/  is id of teh video', max_length=255, verbose_name='Small video Link Id'),
        ),
    ]
